#!/bin/bash
alias set-debug="DEBUG_MALLOC='foo'; export DEBUG_MALLOC";
alias set-lib="LD_LIBRARY_PATH=$PWD/lib:$PWD/lib64:$LD_LIBRARY_PATH; export LD_LIBRARY_PATH"
alias set-nico="LD_LIBRARY_PATH=; export LD_LIBRARY_PATH; LD_LIBRARY_PATH=$PWD/nico/lib:$PWD/nico/lib64:$LD_LIBRARY_PATH; export LD_LIBRARY_PATH"
#alias set_lib="LD_LIBRARY_PATH=$PWD/lib:$LD_LIBRARY_PATH; export LD_LIBRARY_PATH"

alias ls="command ls"
alias l="ls -lF" # all files, in long format
alias la="ls -laF" # all files inc dotfiles, in long format
alias lsd='ls -lF | grep "^d"' # only directories

# Quicker navigation
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."

# Enable aliases to be sudo’ed
alias sudo='sudo '

# Git
# You must install Git first - ""
alias gs='git status'
alias ga='git add .'
alias gc='git commit -m' # requires you to type a commit message
alias gp='git push'

# init z! (https://github.com/rupa/z)
#. ~/z.sh

alias diff="colordiff"

alias gc="ping -c 3 google.com"

alias reconnect="sudo netcfg -r home"
alias shutdown="sudo systemctl poweroff"
alias reboot="sudo systemctl reboot"
alias suspend="sudo pm-suspend"

alias pinstall="sudo pacman -S"
alias update="sudo pacman -Syu"
alias updatef="sudo pacman -Syyuu"
alias updatee="sudo pacman -Syu; cower -uv"

alias sprunge="curl -F 'sprunge=<-' http://sprunge.us"

alias starcraft="wine /home/robin/.wine/drive_c/Program\ Files/StarCraft\ II/StarCraft\ II.exe>/dev/null 2>&1 &"
alias steam="wine /home/robin/.wine-steam/drive_c/Program\ Files/Steam/Steam.exe>/dev/null 2>&1 &"

alias omup="omup -s"

#~/github/bin/

alias screenshot="~/github/scripts/screenshot"
alias imgur="~/github/scripts/imgur"
